apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-deployment
  labels:
    app: content
spec:
  replicas: 3
  selector:
    matchLabels:
      app: content
  template:
    metadata:
      labels:
        app: content
    spec:
      containers:
      - name: content
        image: 
        ports:
        - containerPort: 3000